robot:

  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    right_wheel: ['joint_front_right', 'joint_rear_right']
    left_wheel: ['joint_front_left', 'joint_rear_left']
    pid: {p: 100.0, i: 0.01, d: 10.0}
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    enable_odom_tf: false

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.39086
    wheel_radius : 0.0661

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.25

    # Base frame_id
    base_frame_id: base_link_Chasis #default: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 20.0   # m/s
        has_acceleration_limits: true
        max_acceleration       : 10.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 40.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 20.0   # rad/s^2


  joint_state_controller:
    
    type: "joint_state_controller/JointStateController"
    publish_rate: 50